---

- name: Install Java
  package:
    state=latest
    name={{ item }}
  with_items: "{{ kairosdb_java_packages }}"

- name: Get the KairosDB RPM
  get_url:
    url=https://github.com/kairosdb/kairosdb/releases/download/v{{ kairosdb_version }}/kairosdb-{{ kairosdb_version }}-1.rpm
    dest=/tmp/kairosdb-{{ kairosdb_version }}-1.rpm
    force=yes

- name: Install KairosDB
  yum:
    name=/tmp/kairosdb-{{ kairosdb_version }}-1.rpm
    state=present

- name: Remove Install File
  file:
    src=/tmp/kairosdb-{{ kairosdb_version }}-1.rpm
    state=absent

- name: Restart KairosDB
  command: /bin/true
  notify: restart kairosdb
