---

- name: Install Java
  package:
    state=latest
    name={{ item }}
  with_items: "{{ kairosdb_java_packages }}"

- name: Get the KairosDB RPM
  get_url:
    url=https://github.com/kairosdb/kairosdb/releases/download/v{{ kairosdb_version }}/kairosdb-{{ kairosdb_version }}-1.rpm
    dest=/tmp/kairosdb-{{ kairosdb_version }}-1.rpm
    force=yes

- name: Install KairosDB
  yum:
    name=/tmp/kairosdb-{{ kairosdb_version }}-1.rpm
    state=present

- name: Remove Install File
  file:
    path=/tmp/kairosdb-{{ kairosdb_version }}-1.rpm
    state=absent

- name: Install KairosDB Config
  template:
    src=kairosdb.properties.j2
    dest=/opt/kairosdb/conf/kairosdb.properties
    mode=0640
    owner={{ kairosdb_user }}
    group={{ kairosdb_group }}

- name: Install KairosDB Logging Config
  template:
    src=logback.xml.j2
    dest=/opt/kairosdb/conf/logging/logback.xml
    mode=0640
    owner={{ kairosdb_user }}
    group={{ kairosdb_group }}

- name: Create Keystore Directory
  file:
    path=/etc/keystore
    state=directory
    mode=0710
    owner={{ kairosdb_user }}
    group={{ kairosdb_group }}

- name: Install SSL Key
  copy:
    content="{{ kairosdb_ssl_key }}"
    dest=/etc/keystore/jetty.key
    mode=0600
    owner={{ kairosdb_user }}
    group={{ kairosdb_group }}

- name: Install SSL Certificate
  copy:
    content="{{ kairosdb_ssl_cert }}"
    dest=/etc/keystore/jetty.crt
    mode=0600
    owner={{ kairosdb_user }}
    group={{ kairosdb_group }}


- name: Secure The PKCS12
  file:
    path=/etc/keystore/jetty.pkcs12
    mode=0600
    owner={{ kairosdb_user }}
    group={{ kairosdb_group }}

- name: Restart KairosDB
  command: /bin/true
  notify: restart kairosdb
